name: lab_sound_ffi
description: graph-based audio engine
version: 0.0.1
repository: https://github.com/xioxin/lab_sound_flutter
homepage: https://github.com/xioxin/lab_sound_flutter
issue_tracker: https://github.com/xioxin/lab_sound_flutter/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^3.0.0
  lints: ^1.0.0
  test: ^1.16.0

ffigen:
  name: 'LabSoundBind'
  description: 'Bindings to LabSound'
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'ffigen/LabSoundHelper.h'
  use-supported-typedefs: true
  dart-bool: true
  compiler-opts-automatic:
    macos:
      include-c-standard-library: true
  #  typedef-map:
  #    'size_t': 'Int64'
  #    'uint64_t': 'Uint64'
  #    'uint8_t': 'Uint8'
  preamble: |
    // ignore_for_file: non_constant_identifier_names
  #   include-directives:
  #     - 'bridging/**/include/**'
  # compiler-opts: '-I./bridging/LabSound/include'

# dart run ffigen
# flutter pub run ffigen
